sudo: required

language: java

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10

services:
  - docker

before_install:
- docker pull jboss/keycloak
- docker run -d -p 8888:8080 -e KEYCLOAK_USER=user -e KEYCLOAK_PASSWORD=password -e DB_VENDOR=H2 jboss/keycloak
- docker ps -a
